### ISSUE TITLE
 Initialization failed

### ISSUE THREAD

**Issue by itzgauravsh** [axiftaj/persistent_shopping_cart#5]
PlatformException(channel-error, Unable to establish connection on channel., null, null)

======== Exception caught by widgets library =======================================================
The following HiveError was thrown building:
Box not found. Did you forget to call Hive.openBox()?

these two error occurred

**Comment by MudasirHussain72** [comment]
Hey @itzgauravsh 

Could you please double-check that you've followed the documentation exactly as outlined? Specifically, ensure that you've called the initialization method await PersistentShoppingCart().init() before any other interactions with the shopping cart.

If you're still facing issues after verifying this, could you provide more details or code snippets where these errors occur? This will help me better understand the problem and provide you with the appropriate assistance to resolve it.

Looking forward to hearing back from you!

**Comment by itzgauravsh** [comment]
main.dart same as you told in youtube video
![Screenshot (182)](https://github.com/axiftaj/persistent_shopping_cart/assets/112344227/94e7a02c-0dd2-49dc-817a-29fcae106084)

**Comment by itzgauravsh** [comment]
and on my menu.dart page i have this error
![Screenshot (183)](https://github.com/axiftaj/persistent_shopping_cart/assets/112344227/7e41ca0c-022f-4a1e-93a8-d60e15aab81d)

**Comment by itzgauravsh** [comment]
????

**Comment by axiftaj** [comment]
@itzgauravsh  have you tried the example code ? 

Also can you please share more details,  like flutter version, package version

**Comment by itzgauravsh** [comment]
To resolve the issue, simply type the command "flutter clear" followed by "flutter pub get" in your terminal. After executing these commands, rebuild your app, and you'll find that PersistentShoppingCart initializes smoothly.
